server:
  servlet:
    context-path: /devterial

spring:
  main:
    banner-mode: OFF
  application:
    name: devterial
  banner:
    charset: 'UTF-8'
  datasource:
    url: jdbc:sqlite:src/main/resources/database/mydatabase.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
  devtools:
    restart:
      additional-exclude: database/*
auth: { secret-key: HtmdKi89LbUhTYKclLiTMk2002HlKjbycVtlPhfjs796/yHkmlhtJys@gaclyko2, exp: 86000000, exp-refresh-token: 1500000, issuer-path: vumaiquan.com }

admin: { name: ADMIN, password: 12345678 }



