server:
  servlet:
    context-path: /devterial

spring:
  application:
    name: devterial
  datasource:
    url: jdbc:sqlite:src/main/resources/database/mydatabase.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: true
    open-in-view: false 

auth:
  secret-key: HtmdKi89LbUhTYKclLiTMk2002HlKjbycVtlPhfjs796/yHkmlhtJys@gaclyko2
  exp: 3600000